name: mkdocs gh-deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install cairo
        run: |
            sudo apt-get update
            sudo apt-get install -y libcairo2-dev
      # requirements.txtからの依存関係インストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build
        run: |
          mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4